In [1]:
import tensorflow as tf
import os
import seaborn

In [2]:
#tf.compat.v1.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
data_root = "/Users/ericdoug/Documents/datas/adult"

In [3]:
train_data_file = os.path.join(data_root, "adult.data.csv")
test_data_file = os.path.join(data_root, "adult.test.csv")

In [7]:
reader = tf.compat.v1.TextLineReader(skip_header_lines=1)

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.TextLineDataset`.


In [8]:
file_queue = tf.compat.v1.train.string_input_producer([train_data_file], num_epochs=1)

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
Instructions for updating:
Prefer Dataset.range instead.
Instructions for updating:
Prefer Dataset.range instead.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.


In [9]:
key, value = reader.read(file_queue)

In [8]:
_CSV_COLUMN_DEFAULTS = [  # 定义每一列的默认值
    [0], [''], [0], [''], [0], [''], [''], [''], [''], [''],
    [0], [0], [0], [''], ['']]

_CSV_COLUMNS = [  # 定义CVS列名
    'age', 'workclass', 'fnlwgt', 'education', 'education_num',
    'marital_status', 'occupation', 'relationship', 'race', 'gender',
    'capital_gain', 'capital_loss', 'hours_per_week', 'native_area',
    'income_bracket'
]

In [11]:
csvcolumn = tf.io.decode_csv(records=value, record_defaults=_CSV_COLUMN_DEFAULTS)

In [12]:
featurecolumnn = [i for i in csvcolumn[1:-1]]

In [13]:
labelcolumn = csvcolumn[-1]

In [14]:
featurecolumnn

[<tf.Tensor 'DecodeCSV:1' shape=() dtype=string>,
 <tf.Tensor 'DecodeCSV:2' shape=() dtype=int32>,
 <tf.Tensor 'DecodeCSV:3' shape=() dtype=string>,
 <tf.Tensor 'DecodeCSV:4' shape=() dtype=int32>,
 <tf.Tensor 'DecodeCSV:5' shape=() dtype=string>,
 <tf.Tensor 'DecodeCSV:6' shape=() dtype=string>,
 <tf.Tensor 'DecodeCSV:7' shape=() dtype=string>,
 <tf.Tensor 'DecodeCSV:8' shape=() dtype=string>,
 <tf.Tensor 'DecodeCSV:9' shape=() dtype=string>,
 <tf.Tensor 'DecodeCSV:10' shape=() dtype=int32>,
 <tf.Tensor 'DecodeCSV:11' shape=() dtype=int32>,
 <tf.Tensor 'DecodeCSV:12' shape=() dtype=int32>,
 <tf.Tensor 'DecodeCSV:13' shape=() dtype=string>]

In [15]:
labelcolumn

<tf.Tensor 'DecodeCSV:14' shape=() dtype=string>

In [13]:
dataset = tf.data.TextLineDataset(train_data_file)
for item in dataset.take(1):
    parsed_output = tf.io.decode_csv(item.numpy(), _CSV_COLUMN_DEFAULTS)
    features = dict(zip(_CSV_COLUMNS, parsed_output))
    labels = features.pop('income_bracket')
    print(f"features: {features}, labels:{labels}")
    print(features['age'].numpy())
    print(features['workclass'].numpy())
    print(tf.equal(labels, ">50K"))

features: {'age': <tf.Tensor: shape=(), dtype=int32, numpy=39>, 'workclass': <tf.Tensor: shape=(), dtype=string, numpy=b' State-gov'>, 'fnlwgt': <tf.Tensor: shape=(), dtype=int32, numpy=77516>, 'education': <tf.Tensor: shape=(), dtype=string, numpy=b' Bachelors'>, 'education_num': <tf.Tensor: shape=(), dtype=int32, numpy=13>, 'marital_status': <tf.Tensor: shape=(), dtype=string, numpy=b' Never-married'>, 'occupation': <tf.Tensor: shape=(), dtype=string, numpy=b' Adm-clerical'>, 'relationship': <tf.Tensor: shape=(), dtype=string, numpy=b' Not-in-family'>, 'race': <tf.Tensor: shape=(), dtype=string, numpy=b' White'>, 'gender': <tf.Tensor: shape=(), dtype=string, numpy=b' Male'>, 'capital_gain': <tf.Tensor: shape=(), dtype=int32, numpy=2174>, 'capital_loss': <tf.Tensor: shape=(), dtype=int32, numpy=0>, 'hours_per_week': <tf.Tensor: shape=(), dtype=int32, numpy=40>, 'native_area': <tf.Tensor: shape=(), dtype=string, numpy=b' United-States'>}, labels:b' <=50K'
39
b' State-gov'
tf.Tensor(Fal